version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask_busfare
    restart: always
    environment:
      - APP_NAME=BusFares
    expose:
      - 8888
    ports:
      - "8888:8888"

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "8888:80"